### ISSUE TITLE
Does WebKit work with this plugin?

### ISSUE THREAD

**Issue by tamtakoe** [gilzoide/objc-gdextension#9]
Thanks for this experiment!

Do you try to use the plugin to import WebKit `#import <WebKit/WebKit.h>`? How to do this import?

**Comment by gilzoide** [comment]
Hey @tamtakoe, I'm glad you are interested in this project =]
So, the way this plugin works is by using the Objective-C runtime to find the classes and execute methods in objects (classes are also objects, that's why ObjectiveCClass inherits ObjectCObject). The `#import <...>` construct is a language feature, which has nothing to do with the runtime. In the runtime, all you need to do is reference the classes directly and call methods in them. I haven't tried, but just accessing `ObjectiveC.WKWebView` should give you the WKWebView class, which you could use to instantiate a web view and make it work.

Now, the problem with WKWebView is that you would probably need to instantiate it with a frame using `-[WKWebView initWithFrame:configuration:]`, with frame being a CGRect, which is a struct, and unfortunatelly this plugin does not support struct as method arguments or return values at this point =/
It wouldn't be too hard supporting basic structs like GCRect, but of course it requires some work and testing (with some crashes in the process).

If all you need is a web view for your iOS app, maybe there is some "web view" plugin for Godot that could work for you use case.

**Comment by tamtakoe** [comment]
Unfortunately there are no WebView plugins for Godot(
I tried to use the module https://github.com/V-Sekai-archive/godot-webview, but I encountered the issue for MacOS compilation https://github.com/godotengine/godot/issues/86533

So, Now I want to use WebView inside GDExtension, but have a trouble with Objective-C compilation

**Comment by gilzoide** [comment]
Ok, gotcha.
To compile an Objective-C++ GDExtension, you can actually use godot-cpp's sample SConstruct and simply change your files' extension from ".cpp" to ".mm". The Objective-C++ compiler is the same as the C++ one and the invocation is exactly the same. Probably would need to add `-framework WebKit` option in the link flags, but that should be it. This project itself uses a SConstruct very similar to godot-cpp's to build a GDExtension implemented using Objective-C++, you could use it as a reference for your own WebView GDExtension.

**Comment by tamtakoe** [comment]
Thanks! I will try

**Comment by gilzoide** [comment]
Hey @tamtakoe, I'll be closing this issue, but feel free to reopen it if there is anything in the same topic to discuss. Also, feel free to create new issues or discussions for different subjects.

I hope your web view works out.
Cheers \o/
